# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy.html
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Update a GitHub commit status via CodePipeline events

# More info about Parameters: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
Parameters:

  ApplicationName:
    Description: 'used to create the name of the application in cloud formation'
    Type: String
    AllowedPattern: '[a-zA-Z0-9-_]*'
    MinLength: 3
    MaxLength: 64
    ConstraintDescription: 'must be a valid application name'

  ApplicationStageName:
    Description: 'used for the de-coupling based on environment (IE: production)'
    Type: String
    AllowedPattern: '[a-zA-Z0-9-_]*'
    MinLength: 1
    MaxLength: 16
    ConstraintDescription: 'must be a valid stage name (IE: dev, staging, production)'

  ApplicationBucket:
    Type: String
    Description: 'Pre-existing S3 bucket that will store the application files for deployment'
    MinLength: 5
    AllowedPattern: "[A-Za-z0-9-_]+"
    ConstraintDescription: 'must be a valid s3 bucket location'

  ApplicationBucketPrefix:
    Type: String
    Description: 'Prefix directory inside the bucket for the application'
    MinLength: 1
    AllowedPattern: "[A-Za-z0-9-_]+"
    ConstraintDescription: 'must be a valid s3 bucket prefix'

  EncryptionKeyID:
    Type: AWS::SSM::Parameter::Value<String>
    Description: "The ID of the KMS key used to decrypt environment variables"
    MinLength: 5

  RepoOwner:
    Type: String
    Description: 'the repository owner or username'
    MinLength: 2
    AllowedPattern: "[A-Za-z0-9-]+"
    ConstraintDescription: 'must be a valid repository username'

  RepoName:
    Type: String
    Description: 'the repository name'
    MinLength: 1
    AllowedPattern: "[A-Za-z0-9-_]+"
    ConstraintDescription: 'must be a valid repository name'

  RepoBranch:
    Type: String
    Description: 'the repository branch that will trigger automatic deployments'
    MinLength: 1
    AllowedPattern: "[A-Za-z0-9-_/]+"
    ConstraintDescription: 'must be a valid branch name'

# More info about MetaData: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-publishing-applications-metadata-properties.html
Metadata:
  AWS::ServerlessRepo::Application:
    Name: !Ref ApplicationName
    Description: 'Update a GitHub commit status via CodePipeline events'
    Author: MrZ
    #ReadmeUrl: README.md
    Labels: ['lambda','github','codepipeline']
    HomePageUrl: !Sub 'https://github.com/${RepoOwner}/${RepoName}'
    SemanticVersion: '0.0.1'
    SourceCodeUrl: !Sub 'https://github.com/${RepoOwner}/${RepoName}'

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    MemorySize: 256
    Timeout: 5
    Runtime: go1.x
    CodeUri: 'functions'
    Environment:
      Variables:
        APPLICATION_STAGE_NAME: !Ref ApplicationStageName
        GITHUB_ACCESS_TOKEN: '{{resolve:secretsmanager:production/github:SecretString:status_personal_token_encrypted}}'

# More info about Resources: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-resources-and-properties.html
Resources:

  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
  StatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref ApplicationName  # Change to "status" ?
      CodeUri: releases/status/.
      Handler: status
      Policies:
        - AWSCodePipelineReadOnlyAccess
        - AWSLambdaBasicExecutionRole
        - KMSDecryptPolicy:
            KeyId: !Ref EncryptionKeyID
      Events:
        Event:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.codepipeline
              detail-type:
                - "CodePipeline Pipeline Execution State Change"
              detail:
                state:
                  - "STARTED"
                  - "SUCCEEDED"
                  - "FAILED"

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html
  StatusFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${StatusFunction}'
      RetentionInDays: 90

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-pipeline.html
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    DependsOn:
      - CodeBuildProject
    Properties:
      Name: !Sub "${ApplicationName}-deployment"
      ArtifactStore:
        Type: S3
        Location: !Ref ApplicationBucket
      RestartExecutionOnUpdate: false
      RoleArn: !GetAtt CodePipelineRole.Arn
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-stages.html
      Stages:
        - Name: Source
          Actions:
            - Name: Source-From-Github
              InputArtifacts: []
              RunOrder: 1
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              OutputArtifacts:
                - Name: SourceCode
              Configuration:
                Owner: !Ref RepoOwner
                Repo: !Ref RepoName
                Branch: !Ref RepoBranch
                PollForSourceChanges: false
                OAuthToken: '{{resolve:secretsmanager:production/github:SecretString:status_personal_token}}'
        - Name: Build
          Actions:
            - Name: Build-and-Deploy-Stack
              RunOrder: 3
              InputArtifacts:
                - Name: SourceCode
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName:
                  Ref: CodeBuildProject

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${ApplicationName}-build-deploy"
      ServiceRole: !Ref CodeBuildRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Type: PLAINTEXT
            Value: !Sub "${AWS::Region}"
          - Name: APPLICATION_NAME
            Type: PLAINTEXT
            Value: !Ref ApplicationName
          - Name: APPLICATION_BUCKET
            Type: PLAINTEXT
            Value: !Ref ApplicationBucket
          - Name: APPLICATION_BUCKET_PREFIX
            Type: PLAINTEXT
            Value: !Ref ApplicationBucketPrefix
          - Name: APPLICATION_STAGE_NAME
            Type: PLAINTEXT
            Value: !Ref ApplicationStageName
          - Name: REPO_OWNER
            Type: PLAINTEXT
            Value: !Ref RepoOwner
          - Name: REPO_NAME
            Type: PLAINTEXT
            Value: !Ref RepoName
          - Name: REPO_BRANCH
            Type: PLAINTEXT
            Value: !Ref RepoBranch
          - Name: GITHUB_ACCESS_TOKEN
            Type: PLAINTEXT
            Value: '{{resolve:secretsmanager:production/github:SecretString:status_personal_token_encrypted}}'
      Source:
        Type: CODEPIPELINE
        BuildSpec: "buildspec.yml"
      TimeoutInMinutes: 15

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-webhook.html
  GithubWebhook:
    Type: AWS::CodePipeline::Webhook
    DependsOn:
      - CodePipeline
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: '{{resolve:secretsmanager:production/github:SecretString:status_personal_token}}'
      RegisterWithThirdParty: 'true'
      Filters:
        - JsonPath: "$.ref"
          MatchEquals: refs/heads/{Branch}
      TargetPipeline: !Ref CodePipeline
      TargetAction: Source-From-Github
      TargetPipelineVersion: !GetAtt CodePipeline.Version

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service:
              - codebuild.amazonaws.com
              - cloudformation.amazonaws.com
              - s3.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service:
              - codepipeline.amazonaws.com
              - s3.amazonaws.com
              #- secretsmanager.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

# More info about Outputs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
Outputs:
  StatusFunction:
    Description: 'Affected Function: Status (ARN)'
    Value: !GetAtt StatusFunction.Arn
  AutomaticDeployment:
    Description: 'CI/CD Integration'
    Value: !Sub 'pushing to ${RepoOwner}/${RepoName}:${RepoBranch} will deploy to: ${ApplicationStageName}'
